### ISSUE TITLE
ParameterDeclaration.getType() runs well with .ts, but not with .js files

### ISSUE THREAD

**Issue by gillesfabre34** [dsherret/ts-simple-ast#1187]
**Describe the bug**

Version: 8.2.0

**To Reproduce**

Assume that we have the following method : 

```ts
function isInteresting(n = 2) {
  return n;
}
```

When I use `ParameterDeclaration.getType()` for the node corresponding to the parameter `n`, it runs well if this function is located in a .ts file, but not in a .js file...

In this case, I have this error : 

```ts
TypeError: Cannot read property 'flags' of undefined
    at Object.getCheckFlags (/Users/utilisateur/Documents/these/cpx-codewars/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:17547:23)
    at getTypeOfSymbol (/Users/utilisateur/Documents/these/cpx-codewars/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:50082:33)
    at getTypeOfNode (/Users/utilisateur/Documents/these/cpx-codewars/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:75787:24)
    at Object.getTypeAtLocation (/Users/utilisateur/Documents/these/cpx-codewars/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript.js:42688:31)
    at TypeChecker.getTypeAtLocation (/Users/utilisateur/Documents/these/cpx-codewars/node_modules/ts-morph/dist/ts-morph.js:16639:74)
    at ParameterDeclaration.getType (/Users/utilisateur/Documents/these/cpx-codewars/node_modules/ts-morph/dist/ts-morph.js:3064:42)

```

Is it normal ? I thought that the behavior would be the same for the two extensions.

Thanks for your help ! :)

**Expected behavior**

**Comment by dsherret** [comment]
I don't know what's going on here, but this should work and yeah it doesn't.

**Comment by dsherret** [comment]
@gillesfabre34 Oh, I figured it out. Make sure to use the `allowJs: true` compiler option (this is compiler API behaviour)
