### ISSUE TITLE
Node.getSymbol() maybe throw error if SourceFile name without 'ts' suffix

### ISSUE THREAD

**Issue by hughfenghen** [dsherret/ts-simple-ast#1247]
When SourceFile name without '.ts' suffix, Node.getSymbol() maybe throw error:   
`TypeError: Cannot read properties of undefined (reading 'members')`

This is my little mistake, suggest to fix it or give some friendly tips, thanks.

Version: 12.0.0

```ts
const prj = new Project()
// file-not-ext => file.ts, the program runs correctly
const sf = prj.createSourceFile('file-not-ext', `
  interface A { x: string }
  interface B {
    getA (): Promise<A>;
  }
`)

const retTypeSymbol = sf.getInterface('B')
  ?.getMethods()
  .map(
    m => m.getReturnTypeNodeOrThrow()
      .getChildrenOfKind(SyntaxKind.Identifier)
  )
  .flat()
  .map(i => i.getSymbol())  // => TypeError: Cannot read properties of undefined (reading 'members')
  .map(i => i?.getName())

console.log(111, retTypeSymbol)
```
**Expected behavior**

Not error, print `111 [Promise]`, or remind that SourceFile name needs '.ts' suffix.

**Comment by dsherret** [comment]
The stack trace is:

```ts
Uncaught TypeError: Cannot read properties of undefined (reading 'members')
    at resolveNameHelper (https://deno.land/x/ts_morph@13.0.3/common/typescript.js:48460:70)
    at resolveName (https://deno.land/x/ts_morph@13.0.3/common/typescript.js:48320:20)
    at resolveEntityName (https://deno.land/x/ts_morph@13.0.3/common/typescript.js:49659:42)
    at getSymbolOfNameOrPropertyAccessExpression (https://deno.land/x/ts_morph@13.0.3/common/typescript.js:84089:30)
    at getSymbolAtLocation (https://deno.land/x/ts_morph@13.0.3/common/typescript.js:84174:28)
    at Object.getSymbolAtLocation (https://deno.land/x/ts_morph@13.0.3/common/typescript.js:47092:31)
    at TypeChecker.getSymbolAtLocation (https://deno.land/x/ts_morph@13.0.3/ts_morph.js:17432:52)
    at Identifier.getSymbol (https://deno.land/x/ts_morph@13.0.3/ts_morph.js:3055:47)
 ```

So it occurs in the compiler API. I'm not sure there's anything I can do here and I'm not sure it's worth reporting to them because the extension on the filename is missing. I agree it would be nice if it didn't error though.

**Comment by hughfenghen** [comment]
Oh, thanks. ^_^
