### ISSUE TITLE
Error replacing tree! Perhaps a syntax error was inserted (Current: FunctionExpression -- New: ArrowFunction).

### ISSUE THREAD

**Issue by jon9090** [dsherret/ts-simple-ast#1248]
**Describe the bug**

Version: ^13.0.2

I try to replace `FunctionExpression` with `ArrowFunction` all over the place in my content.

But I got an error:  (full error bellow)
```
Error replacing tree! Perhaps a syntax error was inserted (Current: FunctionExpression -- New: ArrowFunction).
```

In the content I have `iife` function contains another `iife` function. not sure what cause it to failed. but this is happens when I have function inside function.

**To Reproduce**

```ts
import { Project } from "ts-morph";

const content = `
class Foo {

  constructor() {
    config.selectorData = (function () {
      return {
        prop1: '',
        prop2: '',
        array: [
          { name: 'Q4', id: 4 },
          { name: 'Q3', id: 3 },
          { name: 'Q2', id: 2 },
          { name: 'Q1', id: 1 },
        ],
        data: (function () {
          const some = 1;
          const more = [];
          for (let index = year; index >= 10; index--) {
            more.push({ name: index, id: index });
          }
          return more;
        })(),
      };
    })();
  }
}
`;
const sourceFile = project.createSourceFile('foo.ts', content);

const nodes = sourceFile.getDescendantsOfKind(SyntaxKind.FunctionKeyword);

if (nodes.length) {
  sourceFile.transform((traversal) => {
    // this will skip visiting the children of the classes
    // if (ts.isClassDeclaration(traversal.currentNode)) return traversal.currentNode;

    const node = traversal.visitChildren();

    if (ts.isFunctionExpression(node)) {
      return ts.factory.createArrowFunction(
        undefined,
        undefined,
        node.parameters,
        undefined,
        ts.factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
        node.body
      );
    }
    return node;
  });
}
```

**Expected behavior**
To replace all the functions with arrow functions.

**error log**
```
/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1428
            throw new common.errors.InvalidOperationError(`Error replacing tree! Perhaps a syntax error was inserted `
                  ^
ManipulationError: Manipulation error: Error replacing tree! Perhaps a syntax error was inserted (Current: FunctionExpression -- New: ArrowFunction).

-- Details --
Path: /Users/user/sandbox/foo.ts
Text: "\nclass Foo {\n\n  constructor() {\n    config.selectorData = (() => {\n    return {\n        prop1: '',\n        prop2: '',\n        array: [\n            { name: 'Q4', id: 4 },\n            { name: 'Q3', id: 3 },\n            { name: 'Q2', id: 2 },\n            { name: 'Q1', id: 1 },\n        ],\n        data: (() => {\n            const some = 1;\n            const more = [];\n            for (let index = year; index >= 10; index--) {\n                more.push({ name: index, id: index });\n            }\n            return more;\n        })(),\n    };\n})();\n  }\n}\n"
Stack: Error: Error replacing tree! Perhaps a syntax error was inserted (Current: FunctionExpression -- New: ArrowFunction).
    at StraightReplacementNodeHandler.handleNode (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1428:19)
    at NodeHandlerHelper.handleForValues (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1375:21)
    at StraightReplacementNodeHandler.handleChildren (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1442:25)
    at StraightReplacementNodeHandler.handleNode (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1432:18)
    at NodeHandlerHelper.handleForValues (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1375:21)
    at StraightReplacementNodeHandler.handleChildren (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1442:25)
    at StraightReplacementNodeHandler.handleNode (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1432:18)
    at NodeHandlerHelper.handleForValues (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1375:21)
    at StraightReplacementNodeHandler.handleChildren (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1442:25)
    at StraightReplacementNodeHandler.handleNode (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:1432:18)
    at throwError (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:2300:19)
    at doManipulation (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:2298:9)
    at replaceSourceFileTextStraight (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:2706:5)
    at SourceFile.transform (/Users/user/sandbox/node_modules/ts-morph/dist/ts-morph.js:3679:9)
    at Object.<anonymous> (/Users/user/sandbox/app.ts:42:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/Users/user/sandbox/node_modules/ts-node/src/index.ts:1459:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/user/sandbox/node_modules/ts-node/src/index.ts:1462:12)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  filePath: '/Users/user/sandbox/foo.ts',
  oldText: '\n' +
    'class Foo {\n' +
    '\n' +
    '  constructor() {\n' +
    '    config.selectorData = (function () {\n' +
    '      return {\n' +
    "        prop1: '',\n" +
    "        prop2: '',\n" +
    '        array: [\n' +
    "          { name: 'Q4', id: 4 },\n" +
    "          { name: 'Q3', id: 3 },\n" +
    "          { name: 'Q2', id: 2 },\n" +
    "          { name: 'Q1', id: 1 },\n" +
    '        ],\n' +
    '        data: (function () {\n' +
    '          const some = 1;\n' +
    '          const more = [];\n' +
    '          for (let index = year; index >= 10; index--) {\n' +
    '            more.push({ name: index, id: index });\n' +
    '          }\n' +
    '          return more;\n' +
    '        })(),\n' +
    '      };\n' +
    '    })();\n' +
    '  }\n' +
    '}\n',
  newText: '\n' +
    'class Foo {\n' +
    '\n' +
    '  constructor() {\n' +
    '    config.selectorData = (() => {\n' +
    '    return {\n' +
    "        prop1: '',\n" +
    "        prop2: '',\n" +
    '        array: [\n' +
    "            { name: 'Q4', id: 4 },\n" +
    "            { name: 'Q3', id: 3 },\n" +
    "            { name: 'Q2', id: 2 },\n" +
    "            { name: 'Q1', id: 1 },\n" +
    '        ],\n' +
    '        data: (() => {\n' +
    '            const some = 1;\n' +
    '            const more = [];\n' +
    '            for (let index = year; index >= 10; index--) {\n' +
    '                more.push({ name: index, id: index });\n' +
    '            }\n' +
    '            return more;\n' +
    '        })(),\n' +
    '    };\n' +
    '})();\n' +
    '  }\n' +
    '}\n'
}
error Command failed with exit code 1.
```

**Comment by jon9090** [comment]
Hi @dsherret can you provide workaround please?

**Comment by jon9090** [comment]
@dsherret any idea for workaround please?

**Comment by dsherret** [comment]
> I try to replace FunctionExpression with ArrowFunction all over the place in my content.

You could use the `node.replaceWithText(...)` function instead of transform as a workaround.

Note to self: the fix to this would be to make `transform` work more like `replaceWithText`. This would be a breaking API change though.

**Comment by jon9090** [comment]
@dsherret this code: https://github.com/dsherret/ts-morph/commit/75c4a75659c4e15e13913e965b6150d54ade5de8 fix the issue? I try to update `ts-morph` to `14.0.0` but the problem still exist (I tested using the code in the issue)

**Comment by dsherret** [comment]
It hasn't been published yet. It's a breaking change so I probably won't publish it for a bit as I want to get a few more fixes in.
