### ISSUE TITLE
Insert into TemplateExpression causes `Manipulation error: Error replacing tree`

### ISSUE THREAD

**Issue by Wyctus** [dsherret/ts-simple-ast#1263]
**Describe the bug**

If I do a manipulation on a `TemplateExpression` which causes a new `TemplateSpan` to be inserted, then ts-morph crashes.

I don't know if this is an error, actually the error message is right, the number of children is really increased. If this is the intended behavior then what is the proper way to achieve this? 

Stack trace:
```
/project-path/node_modules/ts-morph/dist/ts-morph.js:1438
            throw new Error(`Error replacing tree: The children of the old and new trees were expected to have the `
                  ^
ManipulationError: Manipulation error: Error replacing tree: The children of the old and new trees were expected to have the same count (2:3).

-- Details --
Path: /project-path/test.ts
Text: "css`a: ${a()};\n b: ${23 * b()};\n c: ${c()};`"
Stack: Error: Error replacing tree: The children of the old and new trees were expected to have the same count (2:3).
    at ParentFinderReplacementNodeHandler.handleChildren (/project-path/node_modules/ts-morph/dist/ts-morph.js:1438:19)
    at ParentFinderReplacementNodeHandler.handleNode (/project-path/node_modules/ts-morph/dist/ts-morph.js:1432:18)
    at ParentFinderReplacementNodeHandler.handleNode (/project-path/node_modules/ts-morph/dist/ts-morph.js:1572:19)
    at NodeHandlerHelper.handleForValues (/project-path/node_modules/ts-morph/dist/ts-morph.js:1375:21)
    at ParentFinderReplacementNodeHandler.handleChildren (/project-path/node_modules/ts-morph/dist/ts-morph.js:1442:25)
    at ParentFinderReplacementNodeHandler.handleNode (/project-path/node_modules/ts-morph/dist/ts-morph.js:1432:18)
    at ParentFinderReplacementNodeHandler.handleNode (/project-path/node_modules/ts-morph/dist/ts-morph.js:1572:19)
    at NodeHandlerHelper.handleForValues (/project-path/node_modules/ts-morph/dist/ts-morph.js:1375:21)
    at ParentFinderReplacementNodeHandler.handleChildren (/project-path/node_modules/ts-morph/dist/ts-morph.js:1442:25)
    at ParentFinderReplacementNodeHandler.handleNode (/project-path/node_modules/ts-morph/dist/ts-morph.js:1432:18)
    at throwError (/project-path/node_modules/ts-morph/dist/ts-morph.js:2300:19)
    at doManipulation (/project-path/node_modules/ts-morph/dist/ts-morph.js:2298:9)
    at insertIntoParentTextRange (/project-path/node_modules/ts-morph/dist/ts-morph.js:2319:5)
    at TemplateMiddle.replaceWithText (/project-path/node_modules/ts-morph/dist/ts-morph.js:3643:9)
    at Object.<anonymous> (/project-path/tools/test.ts:25:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/project-path/node_modules/ts-node/src/index.ts:1459:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/project-path/node_modules/ts-node/src/index.ts:1462:12)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  filePath: '/project-path/test.ts',
  oldText: 'css`a: ${a()};\n b: 23;\n c: ${c()};`',
  newText: 'css`a: ${a()};\n b: ${23 * b()};\n c: ${c()};`'
}
```

Version: 14.0.0

**To Reproduce**

```ts
import { Project, SyntaxKind } from "ts-morph";

/*
    css`
    a: ${a()};
    b: 23;
    c: ${c()};
    `
*/
const content: string = "css`a: ${a()};\n b: 23;\n c: ${c()};`";

const project = new Project();
const file = project.createSourceFile("test.ts", content);

const expression = file.getFirstChildByKindOrThrow(SyntaxKind.ExpressionStatement);
const taggedTemplate = expression.getFirstChildByKindOrThrow(SyntaxKind.TaggedTemplateExpression);
const template = taggedTemplate.getFirstChildByKindOrThrow(SyntaxKind.TemplateExpression);
// Span is like this: a()}; b: 23; c: ${
const firstSpan = template.getFirstChildByKindOrThrow(SyntaxKind.TemplateSpan);
// Middle is like this: }; b: 23; c: ${
const middle = firstSpan.getFirstChildByKindOrThrow(SyntaxKind.TemplateMiddle);
// Replaced is like this: }; b: ${23 * b()}; c: ${   This will create one extra TemplateSpan
const newMiddleText = middle.getText().replace("23", "${23 * b()}");

middle.replaceWithText(newMiddleText);

/*
    Should look like this at the end:

    css`
    a: ${a()};
    b: ${23 * b()};
    c: ${c()};
    `
*/

const result = project.emitToMemory();
```

**Expected behavior**

I was expecting that the new `TemplateSpan` will be inserted without a crash.

**Comment by ICodeMyOwnLife** [comment]
@Wyctus I think you should remove

```ts
// Span is like this: a()}; b: 23; c: ${
const firstSpan = template.getFirstChildByKindOrThrow(SyntaxKind.TemplateSpan);
// Middle is like this: }; b: 23; c: ${
const middle = firstSpan.getFirstChildByKindOrThrow(SyntaxKind.TemplateMiddle);
// Replaced is like this: }; b: ${23 * b()}; c: ${   This will create one extra TemplateSpan
const newMiddleText = middle.getText().replace("23", "${23 * b()}");

middle.replaceWithText(newMiddleText);
```

and replace it with

```ts
template.replaceWithText(template.getText().replace("23", "${23 * b()}"));
```

What you do is actually inserting a `TemplateMiddle` inside another `TemplateMiddle` and I guess that is not allowed.

**Comment by Wyctus** [comment]
@ICodeMyOwnLife  
I completely overlooked this fact, you are absolutely right! Thank you!
