### ISSUE TITLE
Error: Not implemented feature for syntax kind 'StringLiteral'.

### ISSUE THREAD

**Issue by remipassmoilesel** [dsherret/ts-simple-ast#129]
Hi, 
Thanks for your amazing job.

I'm trying to use your project but I have some errors. I try to parse a typescript file, in a directory. This file contains several classes and interfaces, and all is parsed correctly except some interfaces.

Example of interface which make tsSimpleAst fail:

```
export interface ITestInterface {
    'features': {
        'landing': {
            'enable': boolean;
            'params': {
                'video': string;
            },
        },
    };
    'studio': string;
    'mail': string;
    'allowedMedia': string[];
    'statistics': string;
    'statisticsApi': string;
}
```

Console ouput: 
```
Error: Not implemented feature for syntax kind 'StringLiteral'.
    at NotImplementedError.Error (native)
    at NotImplementedError.BaseError [as constructor] (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/ts-simple-ast/dist/errors/BaseError.js:16:28)
    at new NotImplementedError (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/ts-simple-ast/dist/errors/NotImplementedError.js:17:28)
    at Object.getNotImplementedForSyntaxKindError (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/ts-simple-ast/dist/errors/helpers.js:75:12)
    at PropertySignature.PropertyNamedNode.class_1.getNameIdentifier (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/ts-simple-ast/dist/compiler/base/name/PropertyNamedNode.js:29:34)
    at PropertySignature.PropertyNamedNode.class_1.getName (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/ts-simple-ast/dist/compiler/base/name/PropertyNamedNode.js:33:25)
    at _.forEach.e (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/src/test/LibrarySchemaSpec.ts:38:50)
    at arrayEach (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/lodash/lodash.js:9359:14)
    at _.forEach (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/src/test/LibrarySchemaSpec.ts:35:19)
    at arrayEach (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/lodash/lodash.js:9359:14)
    at Context.it (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/src/test/LibrarySchemaSpec.ts:33:15)
    at f_promise_1.run (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/f-mocha/src/index.ts:18:17)
    at  (/home/remipassmoilesel/projects/cpos/packages/services/bee-library-admin-service/node_modules/f-promise/build/src/index.js:51:16)

```

My code:
```
            import tsSimpleAst, { SourceFile } from 'ts-simple-ast';
            
            const ast = new tsSimpleAst();
            ast.addSourceFiles(`${configRootPath}/**/*{.d.ts,.ts}`);

            _.forEach(sourceFile.getInterfaces(), (interf) => {
                console.log('Interface: ' + interf.getName());
                _.forEach(interf.getProperties(), (prop) => {

                    try {
                        console.log(`name=${prop.getName()}`);
                    } catch (e) {
                        console.log(`Error: ${e.message}`);
                        console.log(`${e.stack}`);
                    }

                });
            });

```

I tried with several version of Typescript:
```
$ node -v
v6.12.0

$ uname -a 
Linux ... 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ tsc -v
Version 2.6.1
(I tried also Version 2.4.2 2.5.0)
```

Thanks !

**Comment by dsherret** [comment]
@remipassmoilesel I haven't implemented this scenario where names can be a string literal (additionally, computed property names are not yet implemented... see #69).

You can get around this for the time being though. Just use this code:

```typescript
const nameNode = prop.getNodeProperty("name");
console.log(`name=${nameNode.getText()}`);
```

**Comment by remipassmoilesel** [comment]
Thanks for your advice !

**Comment by dsherret** [comment]
This is implemented in 0.93.0. You don't have to do the workaround anymore.

**Comment by remipassmoilesel** [comment]
Great ! I used your library in my project, it was very helpful, much more readable than using directly the TS compiler. 

👍👍👍

**Comment by dsherret** [comment]
Cool. I'm glad it's been useful for you :)
