### ISSUE TITLE
node.setOrder() throws ManipulationError if comment is present

### ISSUE THREAD

**Issue by maxpatiiuk** [dsherret/ts-simple-ast#1462]
**Describe the bug**

Version: 20.0.0
Node.js v20.5.0
TS Node: 10.9.1

**To Reproduce**

Save this file as `bug.mts`:

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile(
  "example.ts",
  `class A {
  constructor() {}
  // IF I REMOVE THIS COMMENT, IT WORKS OK

  /** A */
  get disabled(): boolean {
    return true;
  }
}
`
);

const myClass = sourceFile.getClassOrThrow("A");

// CRASHES HERE:
myClass.getGetAccessorOrThrow("disabled").setOrder(0);
```

Run it:

```sh
node --no-warnings=ExperimentalWarning --loader ts-node/esm/transpile-only ./bug.mts
```

See the error:

```yaml

<redacted>/node_modules/ts-morph/dist/ts-morph.js:2325
            throw new ManipulationError(sourceFile.getFilePath(), oldFileText, newFileText, message);
                  ^

ManipulationError: Manipulation error: Error replacing tree! Perhaps a syntax error was inserted (Current: GetAccessor -- New: SingleLineCommentTrivia).

-- Details --
Path: <redacted>/example.ts
Text: "class A {\n  // IF I REMOVE THIS COMMENT, IT WORKS OK\n\n  /** A */\n  get disabled(): boolean {\n    return true;\n  }\n\n  constructor() {}\n}\n"
Stack: Error: Error replacing tree! Perhaps a syntax error was inserted (Current: GetAccessor -- New: SingleLineCommentTrivia).
    at StraightReplacementNodeHandler.handleNode (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1453:19)
    at NodeHandlerHelper.handleForValues (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1400:21)
    at ChangeChildOrderParentHandler.handleNode (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1484:25)
    at ParentFinderReplacementNodeHandler.handleNode (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1594:36)
    at NodeHandlerHelper.handleForValues (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1400:21)
    at ParentFinderReplacementNodeHandler.handleChildren (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1467:25)
    at ParentFinderReplacementNodeHandler.handleNode (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1457:18)
    at ParentFinderReplacementNodeHandler.handleNode (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1597:19)
    at NodeHandlerHelper.handleForValues (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1400:21)
    at ParentFinderReplacementNodeHandler.handleChildren (<redacted>/node_modules/ts-morph/dist/ts-morph.js:1467:25)
    at throwError (<redacted>/node_modules/ts-morph/dist/ts-morph.js:2325:19)
    at doManipulation (<redacted>/node_modules/ts-morph/dist/ts-morph.js:2323:9)
    at changeChildOrder (<redacted>/node_modules/ts-morph/dist/ts-morph.js:2593:5)
    at GetAccessorDeclaration.setOrder (<redacted>/node_modules/ts-morph/dist/ts-morph.js:5889:13)
    at file:///<redacted>/bug.mts:15:43
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  filePath: '/<redacted>/example.ts',
  oldText: 'class A {\n' +
    '  constructor() {}\n' +
    '  // IF I REMOVE THIS COMMENT, IT WORKS OK\n' +
    '\n' +
    '  /** A */\n' +
    '  get disabled(): boolean {\n' +
    '    return true;\n' +
    '  }\n' +
    '}\n',
  newText: 'class A {\n' +
    '  // IF I REMOVE THIS COMMENT, IT WORKS OK\n' +
    '\n' +
    '  /** A */\n' +
    '  get disabled(): boolean {\n' +
    '    return true;\n' +
    '  }\n' +
    '\n' +
    '  constructor() {}\n' +
    '}\n'
}
```

(Possible cause) It looks like the code has a check for whether manipulation caused a bug, and that check results in a false positive when a comment is present:

![Screenshot 2023-10-17 at 14 31 39](https://github.com/dsherret/ts-morph/assets/40512816/17295a4a-6457-492b-b654-096691e22986)

**Expected behavior**

Node is moved without an error

**Comment by maxpatiiuk** [comment]
Found another case where comments cause an error:

When calling `node.remove()` (where node.getKind() === SyntaxKind.JSDoc), it may throw this error if JS Doc has inline comments around it:

```yaml
Error: Error replacing tree: The children of the old and new trees were expected to have the same count (183:188).
    at ParentFinderReplacementNodeHandler.handleChildren (ts-morph.js:1463:19)
    at ParentFinderReplacementNodeHandler.handleNode (ts-morph.js:1457:18)
    at ParentFinderReplacementNodeHandler.handleNode (ts-morph.js:1597:19)
    at NodeHandlerHelper.handleForValues (ts-morph.js:1400:21)
    at ParentFinderReplacementNodeHandler.handleChildren (ts-morph.js:1467:25)
    at ParentFinderReplacementNodeHandler.handleNode (ts-morph.js:1457:18)
    at ParentFinderReplacementNodeHandler.handleNode (ts-morph.js:1597:19)
    at NodeHandlerHelper.handleForValues (ts-morph.js:1400:21)
    at ParentFinderReplacementNodeHandler.handleChildren (ts-morph.js:1467:25)
    at ParentFinderReplacementNodeHandler.handleNode (ts-morph.js:1457:18)
```

![Screenshot 2023-10-20 at 16 00 17](https://github.com/dsherret/ts-morph/assets/40512816/be41bd43-57b7-4ed8-8e7f-1ab21df5a261)

![Screenshot 2023-10-20 at 16 00 33](https://github.com/dsherret/ts-morph/assets/40512816/0009a553-be4d-4012-b257-bbdf89c04ef1)

My workaround for this is to remove the node through calling .replaceWithText() on it's parent.
For .setOrder(), the (poor) workaround is to remove all inline comments before reordering and then try to add them back.

**Comment by maxpatiiuk** [comment]
Similarly, fails in if you have:

```ts
class A {
 
  a = null!; // some comment

  b = null;
}
```

(then try to move the "b" property)

**Comment by maxpatiiuk** [comment]
Also fails for multi-line comments (with exception of JS Doc)

```ts
class A {
 
  a = null!;
  
  /*
   * error!
   */
  b = null;
}
```
