### ISSUE TITLE
sourceFile.getReferencingLiteralsInOtherSourceFiles() throws when using importHelpers tsconfig option

### ISSUE THREAD

**Issue by mitchlloyd** [dsherret/ts-simple-ast#316]
Adding the `importHelpers: true` tsconfig option causes the `sourceFile.getReferencingLiteralsInOtherSourceFiles()` method to throw:

```
/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/utils/references/LazyReferenceCoordinator.js:47
            finally { if (e_1) throw e_1.error; }
                               ^

TypeError: Cannot read property 'kind' of undefined
    at CompilerFactory.getNodeFromCompilerNode (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:284:25)
    at ImportDeclaration.Node.getNodeFromCompilerNode (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/compiler/common/Node.js:1545:44)
    at ImportDeclaration.getModuleSpecifier (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/compiler/file/ImportDeclaration.js:32:36)
    at ImportDeclaration.getModuleSpecifierSourceFile (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/compiler/file/ImportDeclaration.js:53:27)
    at SourceFileReferenceContainer.getSourceFileForLiteral (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/utils/references/SourceFileReferenceContainer.js:203:27)
    at /Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/utils/references/SourceFileReferenceContainer.js:186:44
    at CompilerFactory.forgetNodesCreatedInBlock (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:537:26)
    at SourceFileReferenceContainer.populateReferences (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/utils/references/SourceFileReferenceContainer.js:174:48)
    at SourceFileReferenceContainer.refresh (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/utils/references/SourceFileReferenceContainer.js:150:14)
    at LazyReferenceCoordinator.refreshDirtySourceFiles (/Users/mitch/projects/ts-project-lint/node_modules/ts-simple-ast/dist/utils/references/LazyReferenceCoordinator.js:39:48)
```

I believe this is because when using `importHelpers`, the first import in `compilerNode.imports` is a synthesized tslib import.

```
[ TokenObject {
    pos: -1,
    end: -1,
    flags: 8,
    kind: 9,
    text: 'tslib' },
```

Then [this line](https://github.com/dsherret/ts-simple-ast/blob/219645154a04058f0e3e5a811882656ea446b2d4/src/compiler/file/ImportDeclaration.ts#L33) expects that the object from `sourceFile.imports` has a `moduleSpecifier` but it does not.

I'm able to get this error with TypeScript 2.7.2 and 2.8.1. 

Unfortunately I could not reproduce this in the sourceFile tests of this project by adding the `importHelpers` option there. I'm hoping that you have a project handy where you could add this option to try it out. Otherwise I'm happy to put together a minimal reproduction in a github repo.

**Comment by dsherret** [comment]
@mitchlloyd hey, thanks again for reporting a bug and for so accurately describing what the problem is! It really helps me get these fixed fast.

I removed synthesized nodes being returned from that (because they have to do with emitting and aren't really relevant to the typescript code). This should be released and fixed in 10.3.3.
