### ISSUE TITLE
Cannot find module './nodeToWrapperMappings'

### ISSUE THREAD

**Issue by svallory** [dsherret/ts-simple-ast#349]
Hi, I'm trying to use v 12.4.0, but trying to import the package gives me this

```
Error: Cannot find module './nodeToWrapperMappings'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/projects/cashfarm/disl/disl-architect-ddd-es/node_modules/ts-simple-ast/dist/factories/index.js:7:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by svallory** [comment]
Looks like the filename was changed to `kindToWrapperMappings`

**Comment by cancerberoSgx** [comment]
just out of curiosity, which npm / nodejs and typescript versions are you using  ? thanks

**Comment by svallory** [comment]
node v8.9.1
typescript 2.9.1

I modified `factories/index.js` to point do `nodeToWrapperMappings.js` and it worked

**Comment by dsherret** [comment]
@svallory I think something went wrong with the install. Can you try deleting the `node_modules` folder and do a fresh install? I just looked at the source code and package and *index.js* is correctly pointing at *kindToWrapperMappings.ts*.

**Comment by svallory** [comment]
@dsherret I have no idea how that happened. But indeed, I reinstalled the package and `factories/index.js` now has the correct code. I'm closing the issue.
