### ISSUE TITLE
Ability to get structure from node

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#45]
The base for this already exists in `createGetStructureFunctions`; however, that should be changed to remove scenario specific logic. The user should be able to do the following:

```typescript
const functionStructure = functionDeclaration.getStructure();

// EDIT: Won't be doing this below. People can modify the returned object when
// they're done themselves.

// or... (return type would be a partial of FunctionDeclarationStructure)
const functionStructure = functionDeclaration.getStructure({
    include: [nameof(AsyncableNode), nameof(GeneratorableNode)]
});

// or... (return type would be a partial of FunctionDeclarationStructure)
const functionStructure = functionDeclaration.getStructure({
    exclude: [nameof(AsyncableNode), nameof(GeneratorableNode)]
});
```

This seems pretty tedious to implement and susceptible to bugs, but these problems can basically be eliminated with code generation.

Left to do (does not include already completed tasks or all tasks):

- [ ] DocumentationableNode
- [ ] ParameteredNode
- [ ] TypeParameteredNode
- [ ] Specific getStructureFunctions
- [ ] Code generate the functions to do this (clean up the old code)

**Comment by cancerberoSgx** [comment]
Hey, I think is a great Idea  being able to generate structures from any node easily  so I can manipulate before add/insert/print. Was searching in the code about this, and this is what I've found: 

* the most useful I found was  this : scripts/common/cloning.ts
 * there is something related here, but I don't think is for the end user: /src/manipulation/helpers/getStructureFunctions.ts 
 src/manipulation/helpers/getMixinStructureFunctions.ts

I'm adding a couple more and refactored your cloning.js so it exposes node2structure() (more generic) functions and based on those the implementation of the current signatures. 
I wonder why these are outside /src/ ? Do you think this is not useful ? or am I missing something? Are these just tools for building the project ? 

From my side I keep adding node2structure since I need this. I would like to contribute these so they get exposed to the end user, but first I would like to know your opinion. Thanks!

**Comment by dsherret** [comment]
I believe I want to completely throw away the `cloning.ts` and `getMixinStructureFunctions.ts` functions in the future and instead use the mixins to help get the structures. It will be something similar to what's shown in `AbstractableNode.getStructure()`.

**Comment by dsherret** [comment]
@cancerberoSgx if you'd like to contribute, I think this would be pretty easy to do. If you'd like to take it on that would be much appreciated! :smile: We just need to add those `getStructure()` methods on each mixin where necessary then also on the classes where a `.getStructure()` method would be useful.

I'm not going to implement what I talked about in this issue with the parameters (ex. `{ exclude: [...etc...] }` thing) because the user can modify the object once they receive it. Not sure what I was thinking originally.

**Comment by cancerberoSgx** [comment]
will  take a look, I was about to add a couple of fixes in clonning.ts glad you told me this  - let's see....

**Comment by cancerberoSgx** [comment]
Hello @dsherret  , I was trying to understand and implement something around getStructure() (starting with  MethodSignature) since I'm currently needing that, but I'm kind of blocked because of the following error I cannot understand. I'm pasting the stack when calling npm run package and npm test . These are the changes I did: https://github.com/cancerberoSgx/ts-simple-ast/commit/dc4a3a0af747c2ddf8803852c7ad11ffb4fc81f0

Regarding if the changes are correct or no (which we can discuss later) I?m worried about not being able to run the tests against those modifications first. 

The error is quite strange because I didn't touched anything related Identifier.ts nor ReferenceFindableNode.ts ... and I cannot figure it out what is causing it. I would really appreciate if you have any ideas or tips. Perhaps I need to run some script / generate code somehow before running the scripts ? 

A couple of notes: I'm able to run npm test and npm run package without errors in non-modified code. I run the commands with older versions of node/npm but same error is thrown. I tried to run all the other scripts in package.json but they all fail the same. 

Thanks in advanced, any help is most appreciated.
 
```
npm run package

> ts-simple-ast@11.2.1 package /home/sg/git/ts-simple-ast
> npm run build && ts-node scripts/createDeclarationFile


> ts-simple-ast@11.2.1 build /home/sg/git/ts-simple-ast
> rimraf dist && npx ttsc


/home/sg/git/ts-simple-ast/src/compiler/common/Identifier.ts:8
export class Identifier extends ReferenceFindableNode(PrimaryExpression)<ts.Identifier> {
                                ^
TypeError: base_1.ReferenceFindableNode is not a function
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/src/compiler/common/Identifier.ts:8:33)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.m._compile (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:403:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:406:12)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

npm test: 

```
npm test

> ts-simple-ast@11.2.1 test /home/sg/git/ts-simple-ast
> cross-env TS_NODE_COMPILER="ttypescript" nyc --reporter=lcov mocha --opts mocha.opts


/home/sg/git/ts-simple-ast/src/compiler/common/Identifier.ts:14
    }
     ^
TypeError: base_1.ReferenceFindableNode is not a function
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/src/compiler/common/Identifier.ts:14:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.replacementCompile (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:403:23)
    at module.exports (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:406:12)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/src/compiler/common/index.ts:1:1605)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.replacementCompile (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:403:23)
    at module.exports (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:406:12)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/src/compiler/base/ModifierableNode.ts:1:19522)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.replacementCompile (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:403:23)
    at module.exports (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:406:12)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/src/compiler/base/index.ts:1:4411)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.replacementCompile (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:403:23)
    at module.exports (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:406:12)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/src/compiler/index.ts:1:1927)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.replacementCompile (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:403:23)
    at module.exports (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:406:12)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/src/tests/compiler/base/ambientableNodeTests.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.replacementCompile (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:403:23)
    at module.exports (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/sg/git/ts-simple-ast/node_modules/ts-node/src/index.ts:406:12)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/sg/git/ts-simple-ast/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/sg/git/ts-simple-ast/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/sg/git/ts-simple-ast/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.replacementCompile (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at runMain (/home/sg/.node-spawn-wrap-20256-5875fbaa4d84/node:68:10)
    at Function.<anonymous> (/home/sg/.node-spawn-wrap-20256-5875fbaa4d84/node:171:5)
    at Object.<anonymous> (/home/sg/git/ts-simple-ast/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at /home/sg/.node-spawn-wrap-20256-5875fbaa4d84/node:178:8
    at Object.<anonymous> (/home/sg/.node-spawn-wrap-20256-5875fbaa4d84/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by dsherret** [comment]
@cancerberoSgx I left some comments on the code. Basically watch out for circular imports... I need to structure the code better in some scenarios.

Thanks again for working on this! 😄

**Comment by cancerberoSgx** [comment]
@dsherret thank you a lot

**Comment by cancerberoSgx** [comment]
Hello @dsherret - your suggestions did work and I was able to have something working. Now I have the following question since I feel I'm doing something wrong - or missing something. For ParameterDeclaration and in general concrete Node classes that use more than one mixins, I had to manually "join" all the structures. Seems that callBaseGetStructure won't do the job here. See

https://github.com/cancerberoSgx/ts-simple-ast/commit/a90db2857b309e9c7b62b1d06a85f905ba1eef12#diff-959faca94e93bc025f2621e069a65d53R86

and this is the function I made for that: 

https://github.com/cancerberoSgx/ts-simple-ast/commit/a90db2857b309e9c7b62b1d06a85f905ba1eef12#diff-6a040eec9a5d36f6a7fb50bca02deab7R21

I really feel I'm missing something here (besides performance and correctness - perhaps a way of doing this automatically ? 

Thanks, any suggestion is most welcome.  Will continue the work using this function - It would be great if you could review it (I won't be offended if you just tell me "this is all wrong please stop working - on the contrary - please do) :)

**Comment by dsherret** [comment]
@cancerberoSgx In `ParameterDeclaration` you should just be able to do this:

```ts
return callBaseGetStructure<ParameterDeclarationSpecificStructure>(ParameterDeclarationBase.prototype, this, {
    isRestParameter: this.isRestParameter()
}) as any as ParameterDeclarationStructure; // might need to add this assertion... I'll make it better later
```

That will work its way down the mixins getting the structure of each one because each mixin should call its base.

**Comment by cancerberoSgx** [comment]
will try thanks! :)
