### ISSUE TITLE
Cannot add decorator if modifier is set

### ISSUE THREAD

**Issue by anthonybriand** [dsherret/ts-simple-ast#90]
Suite of ticket #89 

**On a class :** 
If I declare decorators factories and set the isExported to true it throw the error : 
```
Error: Error replacing tree! Perhaps a syntax error was inserted (Current: ExportKeyword -- New: Decorator).

Code:
@HOInherit()
    at BaseError (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/errors/BaseError.js:5:9)
    at InvalidOperationError (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/errors/InvalidOperationError.js:6:9)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:57:19)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:65:17)
    at handleChangingParent (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:78:13)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:63:17)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:65:17)
    at replaceTree (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:53:9)
    at Object.replaceTreeCreatingSyntaxList (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:13:5)
    at Object.insertSyntaxList (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/insertion/insertSyntaxList.js:12:12)
```

**On a property :** 
If I declare decorators factories and set the scope to private it throw the error : 
```
Error: Error replacing tree! Perhaps a syntax error was inserted (Current: PrivateKeyword -- New: Decorator).

Code:
    @HOField()
    at BaseError (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/errors/BaseError.js:5:9)
    at InvalidOperationError (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/errors/InvalidOperationError.js:6:9)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:57:19)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:65:17)
    at handleChangingParent (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:78:13)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:63:17)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:65:17)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:65:17)
    at handleNode (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:65:17)
    at replaceTree (/Users/acidspike/Development/Sources/SCM/External/TSSimpleAst/dist/manipulation/tree/replaceTree.js:53:9)
```

You will find below an example, which can help you to reproduce and correct these errors : 
```
const sourceFile = ast.addSourceFileFromStructure('./test.ts', {
    imports: [
        {
            namedImports: [
                {
                    name: 'HOModel'
                },
                {
                    name: 'HOInherit'
                },
                {
                    name: 'HOMapping'
                },
                {
                    name: 'HOConnectionInfo'
                },
                {
                    name: 'HOField'
                }
            ],
            moduleSpecifier: '@harmony/orm'
        }
    ],
    classes: [
        {
            name: 'TestModel',
            'extends': 'HOModel',
            isExported: true,
            decorators: [
                {
                    name: 'HOInherit',
                    arguments: []
                },
                {
                    name: 'HOMapping',
                    arguments: [
                        '\'test\''
                    ]
                },
                {
                    name: 'HOConnectionInfo',
                    arguments: [
                        '\n    {\n        connectionName: \'test\'\n    }\n'
                    ]
                }
            ],
            properties: [
                {
                    name: 'test',
                    type: 'string',
                    decorators: [
                        {
                            name: 'HOField',
                            arguments: []
                        }
                    ],
                    scope: 'private',
                    initializer: 'null'
                }
            ],
            methods: [
                {
                    name: 'getTest',
                    bodyText: 'return this.test;',
                    returnType: 'string'
                },
                {
                    name: 'setTest',
                    parameters: [
                        {
                            name: 'test',
                            type: 'string'
                        }
                    ],
                    bodyText: 'this.test = test;\nreturn this;',
                    returnType: 'this'
                }
            ]
        }
    ]
});

console.log(sourceFile.getFullText()); // Throw errors
```

**Comment by dsherret** [comment]
This is fixed in 0.71.1. Thank you for reporting it! Sorry about not looking at this yesterday when you mentioned it... I had a very busy day.

**Comment by dsherret** [comment]
This should actually also fix some unsurfaced issues. It's basically the inverse of the issue yesterday.

**Comment by anthonybriand** [comment]
Hi,
Do not apologize, we all have a life outside of our projects, I confirm that the fix has worked, thank you.
